### ISSUE TITLE
Confirming dialog with ↵ leaves `result` undefined

### ISSUE THREAD

**Issue by johanneseckert** [pklaschka/xd-dialog-helper#10]
### Description of the bug
When confirming the dialog with the return key, `result` is undefined

### Code example
The above happens when I attempt to run the following snippet of code:

```javascript
const DialogHelper = require('xd-dialog-helper');

function myFunction(selection) {
    DialogHelper.showDialog('hello-xd-dialog-helper', 'Hello xd-dialog-helper!', [
        {
            type: DialogHelper.HR,
            id: 'myHR'
        },
        {
            type: DialogHelper.TEXT_INPUT,
            id: 'userName',
            label: 'Your Name:'
        }
    ], {}).then((results) => {
        // Dialog got accepted
        console.log('Hello ' + results['userName'] + '!');
    }, (reason) => {
        // Dialog got rejected
        console.log('The dialog got rejected');
    });
}
```

**Version:** `0.9.2`

### Additional information:
macOS 10.14.2
XD 14.0

**Comment by pklaschka** [comment]
@johanneseckert 
That shouldn't happen (although I think I know why it happens).

Thank you very much for bringing this up. Could you possibly check if it is also `undefined` when you use
```javascript
const DialogHelper = require('xd-dialog-helper');

function myFunction(selection) {
    DialogHelper.showDialog('hello-xd-dialog-helper', 'Hello xd-dialog-helper!', [
        {
            type: DialogHelper.HR,
            id: 'myHR'
        },
        {
            type: DialogHelper.TEXT_INPUT,
            id: 'userName',
            label: 'Your Name:',
            value: 'Hello World'
        }
    ], {}).then((results) => {
        // Dialog got accepted
        console.log('Hello ' + results['userName'] + '!');
    }, (reason) => {
        // Dialog got rejected
        console.log('The dialog got rejected');
    });
}
```
If it also happens with this code (which I'd expect), I at least have an idea (which would be good, since I don't have access to a Mac the next few days and don't want to leave you with this bug for this amount of time). Since this doesn't happen on Windows (since dialogs can't get "submitted" by pressing enter there), I, unfortunately, can't debug this right now.

Sorry that I'm not really able to help you much with this at the moment (I'll also contact Adobe to ask how the "Enter" behavior on macOS can get handled), but I'll look into it as soon as I can.

Best,
Pablo

**Comment by johanneseckert** [comment]
yes — no difference. also doesn't make a different when I remove the text input, since then the next object gets focus.

Thank you for looking into this. Luckily, I'm not pressured for time with this :)

**Comment by pklaschka** [comment]
@johanneseckert Alright, then I at least suspect to know what the problem is 😅 

> Luckily, I'm not pressured for time with this :)

That's good to hear 😉 – I'll let you know as soon as I have any news on this.

**Comment by johanneseckert** [comment]
yup, this fixes this issue! 👍

**Comment by pklaschka** [comment]
@johanneseckert Great to hear, thank you.
