### ISSUE TITLE
Update slider values in realtime

### ISSUE THREAD

**Issue by johanneseckert** [pklaschka/xd-dialog-helper#16]
Currently, Slider Values do not update during drag, only on mouse up. This makes it difficult to hit an exact value.
![dialog](https://user-images.githubusercontent.com/545926/50925496-5bdc4680-1407-11e9-9418-c8e47272954e.gif)

**Comment by pklaschka** [comment]
This is fixed with v1.0.0, which is currently in Beta. You can already use it by using

```
npm install xd-dialog-helper@next
```

see https://github.com/pklaschka/xd-dialog-helper/releases/tag/v1.0.0-beta.0 for further reference and a guide to migrating to the new version (which shouldn't take more than editing a few lines of code, changing `dialogHelper.[TYPE]` to `dialogHelper.types.[TYPE]` 😉
