### ISSUE TITLE
Add to XD-Awesome

### ISSUE THREAD

**Issue by ashryanbeats** [pklaschka/xd-dialog-helper#19]
@pklaschka, Are you planning to add this one to XD-Awesome?

The word "awesome" is used no less than 4 times in response to your forum thread about this tool:
https://forums.adobexdplatform.com/t/xd-dialog-helper-a-helper-library-to-make-dealing-with-dialogs-easy/450/7

**Comment by pklaschka** [comment]
@ashryanbeats Thank you very much – I plan to suggest it's addition once I've released v1.0.

Currently, I'm making a few (partially breaking) changes (mostly to the "internal" structure) to support many features I'd like to add after v1.0 (e.g., custom elements and much more) and therefore, it should still be considered to be in a prerelease state right now. Since I don't want to make severe changes for a while after releasing v1.0 (to make the UX of using the library as pleasant as possible), this means that I'm currently introducing a lot of changes.

Once that is completed (I currently hope this will be before the end of this month), I'll "mark" it as v1.0 (without many new features, but a stable structure to add those features) and also request/suggest/whatever its addition to XD-Awesome.

Since, however, the library provides a very high level of abstraction, I can get a lot wrong with it (this level of abstraction only works out when it feels *right*, and I'm not *quite* there yet). I don't want to include it in the list before I can confidently say it has reached that stage of being production-ready. As soon as I feel like it's ready, however, you can expect to see a pull request for it in the XD-Awesome repo 😉
