### ISSUE TITLE
Feature: Sections

### ISSUE THREAD

**Issue by johanneseckert** [pklaschka/xd-dialog-helper#20]
For longer settings dialogs, it could be helpful to start section controls and make them collabsible

A section could include all controls until the next section (or the end of the dialog)

![image](https://user-images.githubusercontent.com/545926/52017375-06420980-249c-11e9-9dfd-267af099fe4d.png)

**Comment by pklaschka** [comment]
Great idea 👍 .

However, I'm currently trying to get the dialog helper to v1.0 (which presently has the highest priority for me). For that, I'm also adjusting the system so that it allows for custom elements types (and therefore changing the internal structure of the library significantly). Since this proposal seems to be a bit more complex (and doesn't correspond to a "standard" UI element from the plugin docs), I first want to get to a v1.0 stage and then (with the revised structure) look into how such "non-standard" cases can get handled. It could, for example, be useful to have an "extra" set of UI components for such cases, handling this specific type of feature (meaning there could also be a set of other, non-standard controls) and make it completely open for third-party contributions, leading to me not being the sole developer covering all controls someone might need.

Therefore, while I like the idea very much, I don't think I'll be able to implement it quickly. It's a "bigger" decision of how to handle such cases, which I want to postpone at least until after the release of v1.0 (which hopefully will be within the next few weeks) and then implement it in a good (rather than in an "easy" or "quick and dirty" kind of) way.

Best,
Pablo
