### ISSUE TITLE
Document how to run async operation after dialog is confirmed

### ISSUE THREAD

**Issue by johanneseckert** [pklaschka/xd-dialog-helper#9]
**Is your feature request related to a problem? Please describe.**
It is unclear to me how to run an await/async function when the dialog is confirmed

**Describe the solution you'd like**
```
  ], {}).then((results) => {
      // Dialog got accepted
      console.log('Dialog confirmed');
      await createTimeline(selection)
```

**Additional context**
There seems to be a syntax error when doing that … `Plugin SyntaxError: await is only valid in async function` — I wonder if you could document how to do this properly in ES6.

Because I fully agree with you, creating dialogs is hard :)

**Comment by pklaschka** [comment]
Hi @johanneseckert 

There are multiple ways to achieve asynchronous code after the dialog got accepted.

One way would be to use 
```javascript
  ], {}).then((results) => {
      // Dialog got accepted
      console.log('Dialog confirmed');
      createTimeline(selection).then(()=>{ /* continue here */ })
```

You could also try it (although I haven't tested that, so no guarantees here 😉) using 
```javascript
  ], {}).then((results) => {
      // Dialog got accepted
      console.log('Dialog confirmed');
      createTimeline(selection).then(()=>{ /* continue here */ })
```

However, this gets quite cumbersome rather quickly and I'd, therefore, suggest using the async/await syntax and write something like

```javascript
async function myFun(selection) {
  try {
    const results = await DialogHelper.showDialog(...);
    // Dialog got accepted
    console.log('Dialog confirmed');
    await createTimeline(selection);
  } catch (e) {
    // Dialog got canceled
  }
}
```

The problem with documenting this is that there isn't really any "right" and "wrong" here and since this is JS-related (and not so much a "special" thing about this library), I'm not quite sure how I could properly document this.

I'll probably add an example in https://github.com/pklaschka/xd-dialog-helper/wiki/Examples with a reference to it in the `showDialog()` section of the wiki.

I hope this helps (for now) – if not, please feel free to let me know and we'll see how we can get this resolved,
Best,
Pablo

**Comment by johanneseckert** [comment]
This is great, thank you!
As someone who gets used to ES6, half of this is over my head—especially parsing all the shorthand. However, your suggestions helped.

With minimal changes to the code structure, I can do
```
], {}).then(async (results) => {…
```
when I *also* add the `await` keyword then showing the dialog
```
await DialogHelper.showDialog(…
```

**Comment by pklaschka** [comment]
@johanneseckert Right, I forgot to mention that.

I've now added an example of how async/await can be used [in the wiki](https://github.com/pklaschka/xd-dialog-helper/wiki/Examples#asynchronous-example), so I'll close the issue. If you feel like the docs don't suffice for that, please feel free to reopen the issue...
